DROP TABLE VETERINARIO IF EXISTS;


CREATE TABLE VETERINARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_LICENCIA VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
ESPECIALIDAD VARCHAR(25) NOT NULL
);

INSERT INTO VETERINARIO VALUES (DEFAULT, '123', 'JORGE','CEBALLOS','CABALLOS');